/**
 * Minimal Pi-SDK agent that optimizes a single Triton kernel at the PTX level.
 *
 * Usage:
 *     node agent.js <KernelId>            (default: AddKernel)
 *
 * Environment variables:
 *     TRITON_PTX_URL   Base URL of the Triton PTX server (see triton_api.js).
 */

import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  createAgentSession,
  DefaultResourceLoader,
  getAgentDir,
  ModelRuntime,
  SessionManager,
  defineTool,
} from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

import {
  dumpKernelPtx,
  evaluateCandidate,
  getKernelData,
  TritonApiError,
} from "./triton_api.js";

// --- Colors ---

const RESET = "\x1b[0m";
const BLUE = "\x1b[34m";
const GREEN = "\x1b[32m";
const RED = "\x1b[31m";
const GRAY = "\x1b[90m";
const CYAN = "\x1b[36m";

const SYSTEM_PROMPT =
  "You are an expert GPU engineer optimizing a single Triton kernel at the " +
  "NVIDIA PTX (assembly) level. You are given the Triton source, the PTX " +
  "signature, the launch configuration, and the reference PTX that Triton " +
  "generates.\n\n" +
  "Your goal is to produce PTX that is functionally identical to the " +
  "reference but runs faster. Call submit_ptx to compile, verify, and " +
  "benchmark a candidate; it returns whether it compiled, whether it is " +
  "correct, its p50 latency, and its speedup versus Triton. Iterate: read " +
  "the result, fix errors, and keep trying to improve the speedup while " +
  "staying correct. Only correct (passing) candidates count. When you are " +
  "satisfied that you cannot improve further, stop and summarize your best " +
  "result.";

// --- Environment context ---

/** Assemble the kernel context handed to the model in the first turn. */
async function buildContextMessage(kernelId) {
  const data = await getKernelData(kernelId);
  const referencePtx = await dumpKernelPtx(kernelId);
  if (!referencePtx) {
    throw new Error(`Triton did not produce reference PTX for ${kernelId}.`);
  }

  const system = data.system;
  const signature = data.ptx_signature
    .map((param) => `  ${param.name}: ${param.ptx_type}`)
    .join("\n");
  const defaultThreadsX = data.num_warps * 32;

  return (
    `Kernel to optimize: ${kernelId}\n` +
    `PTX kernel name: ${data.kernel_name}\n\n` +
    `Target: ${system.target} | PTX version: ${system.version} | ` +
    `address size: ${system.address_size}\n` +
    `num_warps: ${data.num_warps} ` +
    `(reference launch uses num_threads_x = ${defaultThreadsX})\n\n` +
    "PTX parameter signature:\n" +
    `${signature}\n\n` +
    "Triton source:\n" +
    "```python\n" +
    `${data.source}\n` +
    "```\n\n" +
    "Reference PTX generated by Triton (a correct starting point):\n" +
    "```ptx\n" +
    `${referencePtx}\n` +
    "```\n\n" +
    "Submit an optimized PTX candidate with submit_ptx."
  );
}

// --- Tool ---

/** Build the single submit_ptx tool bound to a kernel id. */
function makeSubmitPtxTool(kernelId, tracker) {
  return defineTool({
    name: "submit_ptx",
    label: "Submit PTX",
    description:
      "Compile, verify, and benchmark a PTX candidate for the kernel. " +
      "Returns whether it compiled, whether it is correct, its p50 latency, " +
      "and its speedup versus the Triton baseline.",
    parameters: Type.Object({
      ptx: Type.String({
        description: "The full PTX module source for the candidate.",
      }),
      num_threads_x: Type.Integer({
        description: "Number of threads per block along x (required).",
      }),
      num_threads_y: Type.Optional(
        Type.Integer({ description: "Number of threads per block along y (optional)." }),
      ),
      num_threads_z: Type.Optional(
        Type.Integer({ description: "Number of threads per block along z (optional)." }),
      ),
    }),
    execute: async (_toolCallId, params) => {
      // The "[call]" marker is rendered from the tool_execution_start event so
      // streaming stays in one place; here we only evaluate and report results.
      let result;
      try {
        result = await evaluateCandidate(kernelId, params);
      } catch (err) {
        // Surface environment/transport errors back to the model as text.
        const message =
          err instanceof TritonApiError
            ? `Evaluation failed (HTTP ${err.status}): ${err.message}`
            : `Evaluation failed: ${err.message}`;
        console.log(`${RED}[error]${RESET} ${GRAY}${message}${RESET}`);
        return {
          content: [{ type: "text", text: JSON.stringify({ error: message }, null, 2) }],
          details: { error: message },
        };
      }

      if (result.passed && result.speedup_vs_triton > tracker.bestSpeedup) {
        tracker.bestSpeedup = result.speedup_vs_triton;
      }

      const tag = result.passed ? `${GREEN}[ok]${RESET}` : `${RED}[fail]${RESET}`;
      const text = JSON.stringify(result, null, 2);
      console.log(`${tag} ${GRAY}${text}${RESET}`);

      return {
        content: [{ type: "text", text }],
        details: {},
      };
    },
  });
}

// --- Agent ---

async function main() {
  const kernelId = process.argv[2] || "AddKernel";
  console.log(`Optimizing kernel ${JSON.stringify(kernelId)} with the Pi SDK`);

  const contextMessage = await buildContextMessage(kernelId);
  const tracker = { bestSpeedup: 0 };
  const submitPtx = makeSubmitPtxTool(kernelId, tracker);

  const loader = new DefaultResourceLoader({
    cwd: process.cwd(),
    agentDir: getAgentDir(),
    systemPromptOverride: () => SYSTEM_PROMPT,
    // Avoid appending any APPEND_SYSTEM.md discovered from disk.
    appendSystemPromptOverride: () => [],
  });
  await loader.reload();

  // Load the model list from the local models.json (next to this file) so its
  // per-model settings -- notably a raised maxTokens -- take effect. Credentials
  // still come from the default agent dir / the $EPFL_API_KEY env var referenced
  // in models.json. Model selection is left to auto-discovery for now.
  const modelsPath = fileURLToPath(new URL("./models.json", import.meta.url));
  const modelRuntime = await ModelRuntime.create({
    modelsPath,
    authPath: path.join(getAgentDir(), "auth.json"),
  });

  const { session } = await createAgentSession({
    customTools: [submitPtx],
    // Restrict to only our tool -- no built-in read/bash/edit, matching the
    // single-tool design of the baseline agent.
    tools: ["submit_ptx"],
    // Stream reasoning too, the way the Pi TUI does (ignored by models that do
    // not support thinking). Adjust with model selection later.
    thinkingLevel: "medium",
    modelRuntime,
    resourceLoader: loader,
    sessionManager: SessionManager.inMemory(),
  });

  // TUI-style streaming: render reasoning (grey) and answer text (cyan) live,
  // with clean transitions between reasoning, text, and tool calls.
  let streamMode = null; // "text" | "thinking" | null
  let lastStopReason = null;

  session.subscribe((event) => {
    switch (event.type) {
      case "message_update": {
        const ev = event.assistantMessageEvent;
        if (ev.type === "thinking_start" || ev.type === "thinking_delta") {
          if (streamMode !== "thinking") {
            process.stdout.write(`\n${GRAY}[thinking] `);
            streamMode = "thinking";
          }
          if (ev.type === "thinking_delta") process.stdout.write(ev.delta);
        } else if (ev.type === "text_start" || ev.type === "text_delta") {
          if (streamMode !== "text") {
            process.stdout.write(`\n${CYAN}`);
            streamMode = "text";
          }
          if (ev.type === "text_delta") process.stdout.write(ev.delta);
        } else if (ev.type === "text_end" || ev.type === "thinking_end") {
          process.stdout.write(RESET);
          streamMode = null;
        }
        break;
      }
      case "tool_execution_start": {
        process.stdout.write(RESET);
        const args = event.args || {};
        const ptxLen = typeof args.ptx === "string" ? `${args.ptx.length} chars` : "?";
        console.log(
          `\n${BLUE}[call]${RESET} ${GRAY}submit_ptx(ptx: ${ptxLen}, ` +
            `num_threads_x: ${args.num_threads_x})${RESET}`,
        );
        streamMode = null;
        break;
      }
      case "turn_end": {
        // Report why each turn ended, so a run that stops without submitting is
        // diagnosable. stopReason "length" means the model hit its output-token
        // cap (maxTokens) mid-generation, likely before calling submit_ptx.
        const msg = event.message || {};
        const usage = msg.usage;
        lastStopReason = msg.stopReason ?? null;
        process.stdout.write(RESET);
        const usageStr = usage
          ? `${usage.output} out` +
            (usage.reasoning != null ? ` (${usage.reasoning} reasoning)` : "") +
            `, ${usage.input} in`
          : "usage n/a";
        console.log(
          `\n${GRAY}[info] stop=${lastStopReason} | ${usageStr}${RESET}`,
        );
        if (lastStopReason === "length") {
          console.log(
            `${RED}[warning]${RESET} ${GRAY}Turn hit the model output-token limit ` +
              `(maxTokens) mid-generation, so it may have stopped before calling ` +
              `submit_ptx. Raise the model's maxTokens or lower thinkingLevel.${RESET}`,
          );
        }
        streamMode = null;
        break;
      }
    }
  });

  try {
    // prompt() resolves only after the full run (all turns + tool calls) ends.
    await session.prompt(contextMessage);
  } finally {
    session.dispose();
  }

  const best =
    tracker.bestSpeedup > 0 ? tracker.bestSpeedup.toFixed(3) + "x" : "none";
  console.log(`\n${GRAY}Done. Best passing speedup vs Triton: ${best}.${RESET}`);
  if (lastStopReason === "length") {
    console.log(
      `${RED}Note:${RESET} ${GRAY}the run ended on a truncated turn (output-token ` +
        `limit), not because the model chose to stop.${RESET}`,
    );
  }
}

main().catch((err) => {
  console.error(`${RED}Fatal:${RESET} ${err.stack || err.message}`);
  process.exitCode = 1;
});
