/**
 * Minimal Pi-SDK agent that optimizes a single Triton kernel at the PTX level.
 *
 * Usage:
 *     node agent.js <KernelId>            (default: AddKernel)
 *
 * Environment variables:
 *     TRITON_PTX_URL   Base URL of the Triton PTX server (see triton_api.js).
 */

import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  createAgentSession,
  DefaultResourceLoader,
  getAgentDir,
  ModelRuntime,
  SessionManager,
} from "@earendil-works/pi-coding-agent";

import { dumpKernelPtx, getKernelData } from "./triton_api.js";
import {
  cleanKernelArtifacts,
  makeSubmitPtxTool,
  makeWorkspaceJail,
  READ_ONLY_TOOL_NAMES,
  SKILL_DIRS,
  WORKSPACE_DIR,
} from "./tool.js";
import { BLUE, CYAN, GRAY, MAGENTA, RED, RESET } from "./tui.js";

const SYSTEM_PROMPT =
  "You are an expert GPU engineer optimizing a single Triton kernel at the " +
  "NVIDIA PTX (assembly) level. You are given the Triton source, the PTX " +
  "signature, the launch configuration, and the reference PTX that Triton " +
  "generates.\n\n" +
  "Your goal is to produce PTX that is functionally identical to the " +
  "reference but runs faster. Call submit_ptx to compile, verify, and " +
  "benchmark a candidate; it returns whether it compiled, whether it is " +
  "correct, its p50 latency, and its speedup versus Triton. Iterate: read " +
  "the result, fix errors, and keep trying to improve the speedup while " +
  "staying correct. Only correct (passing) candidates count. When you are " +
  "satisfied that you cannot improve further, stop and summarize your best " +
  "result." +
  "You can use your tools to read the PTX documentation, provided as a skill." +
  "Your tools can only access data in the `agent_workspace`.";

// --- Environment context ---

/** Assemble the kernel context handed to the model in the first turn. */
async function buildContextMessage(kernelId) {
  const data = await getKernelData(kernelId);
  const referencePtx = await dumpKernelPtx(kernelId);
  if (!referencePtx) {
    throw new Error(`Triton did not produce reference PTX for ${kernelId}.`);
  }

  const system = data.system;
  const signature = data.ptx_signature
    .map((param) => `  ${param.name}: ${param.ptx_type}`)
    .join("\n");
  const defaultThreadsX = data.num_warps * 32;

  return (
    `Kernel to optimize: ${kernelId}\n` +
    `PTX kernel name: ${data.kernel_name}\n\n` +
    `Target: ${system.target} | PTX version: ${system.version} | ` +
    `address size: ${system.address_size}\n` +
    `num_warps: ${data.num_warps} ` +
    `(reference launch uses num_threads_x = ${defaultThreadsX})\n\n` +
    "PTX parameter signature:\n" +
    `${signature}\n\n` +
    "Triton source:\n" +
    "```python\n" +
    `${data.source}\n` +
    "```\n\n" +
    "Reference PTX generated by Triton (a correct starting point):\n" +
    "```ptx\n" +
    `${referencePtx}\n` +
    "```\n\n" +
    "Submit an optimized PTX candidate with submit_ptx."
  );
}

// --- Agent ---

async function main() {
  const kernelId = process.argv[2] || "AddKernel";
  console.log(`Optimizing kernel ${JSON.stringify(kernelId)} with the Pi SDK`);

  // Clear kernel-<id>.ptx / kernel-result-<id>.json from any previous run so
  // this session's submit counter starts from a clean workspace.
  const cleaned = cleanKernelArtifacts();
  if (cleaned > 0) {
    console.log(`${GRAY}Cleared ${cleaned} kernel artifact(s) from a previous run.${RESET}`);
  }

  const contextMessage = await buildContextMessage(kernelId);
  const tracker = { bestSpeedup: 0 };

  // Persist the run as an append-only JSONL session tree so it can be analyzed
  // later. Stored under pi_agent/sessions/ (gitignore it to keep runs local).
  // Inspect with `pi --session <file>` or by reading the JSONL directly.
  const sessionsDir = fileURLToPath(new URL("./sessions", import.meta.url));
  const sessionManager = SessionManager.create(WORKSPACE_DIR, sessionsDir);
  console.log(`${MAGENTA}Session log: ${sessionManager.getSessionFile()}${RESET}`);

  // The session id is embedded in saved best-kernel filenames so each record
  // links back to this run's session.
  const submitPtx = makeSubmitPtxTool(
    kernelId,
    tracker,
    sessionManager.getSessionId(),
  );

  const loader = new DefaultResourceLoader({
    // Run tools out of the workspace so relative paths resolve there and the
    // read-only tools default to it; the jail below blocks anything outside it.
    cwd: WORKSPACE_DIR,
    agentDir: getAgentDir(),
    systemPromptOverride: () => SYSTEM_PROMPT,
    // Avoid appending any APPEND_SYSTEM.md discovered from disk.
    appendSystemPromptOverride: () => [],
    // Advertise the bundled skills (name + description) to the model. Pi appends
    // the skills section to our custom system prompt because the read tool is
    // enabled; the model then reads SKILL.md on demand via the read-only tools.
    additionalSkillPaths: SKILL_DIRS,
    // Confine the built-in read-only tools to WORKSPACE_DIR (skills live there).
    extensionFactories: [makeWorkspaceJail()],
  });
  await loader.reload();

  // Load the model list from the local models.json (next to this file) so its
  // per-model settings -- notably a raised maxTokens -- take effect. Credentials
  // still come from the default agent dir / the $EPFL_API_KEY env var referenced
  // in models.json. Model selection is left to auto-discovery for now.
  const modelsPath = fileURLToPath(new URL("./models.json", import.meta.url));
  const modelRuntime = await ModelRuntime.create({
    modelsPath,
    authPath: path.join(getAgentDir(), "auth.json"),
  });

  const { session } = await createAgentSession({
    cwd: WORKSPACE_DIR,
    customTools: [submitPtx],
    // Enable submit_ptx plus the built-in read-only tools (read/ls/grep/find),
    // which the workspace jail confines to WORKSPACE_DIR. No write/edit/bash.
    tools: ["submit_ptx", ...READ_ONLY_TOOL_NAMES],
    // Stream reasoning too, the way the Pi TUI does (ignored by models that do
    // not support thinking). Adjust with model selection later.
    thinkingLevel: "medium",
    modelRuntime,
    resourceLoader: loader,
    sessionManager,
  });

  // TUI-style streaming: render reasoning (grey) and answer text (cyan) live,
  // with clean transitions between reasoning, text, and tool calls.
  let streamMode = null; // "text" | "thinking" | null
  let lastStopReason = null;

  session.subscribe((event) => {
    switch (event.type) {
      case "message_update": {
        const ev = event.assistantMessageEvent;
        if (ev.type === "thinking_start" || ev.type === "thinking_delta") {
          if (streamMode !== "thinking") {
            process.stdout.write(`\n${GRAY}[thinking] `);
            streamMode = "thinking";
          }
          if (ev.type === "thinking_delta") process.stdout.write(ev.delta);
        } else if (ev.type === "text_start" || ev.type === "text_delta") {
          if (streamMode !== "text") {
            process.stdout.write(`\n${CYAN}`);
            streamMode = "text";
          }
          if (ev.type === "text_delta") process.stdout.write(ev.delta);
        } else if (ev.type === "text_end" || ev.type === "thinking_end") {
          process.stdout.write(RESET);
          streamMode = null;
        }
        break;
      }
      case "tool_execution_start": {
        process.stdout.write(RESET);
        const args = event.args || {};
        let summary;
        if (event.toolName === "submit_ptx") {
          const ptxLen = typeof args.ptx === "string" ? `${args.ptx.length} chars` : "?";
          summary = `submit_ptx(ptx: ${ptxLen}, num_threads_x: ${args.num_threads_x})`;
        } else {
          // Read-only tools (read/ls/grep/find): show the most useful arg.
          const detail = args.pattern ?? args.path ?? "";
          summary = `${event.toolName}(${detail})`;
        }
        console.log(`\n${BLUE}[call]${RESET} ${GRAY}${summary}${RESET}`);
        streamMode = null;
        break;
      }
      case "turn_end": {
        // Report why each turn ended, so a run that stops without submitting is
        // diagnosable. stopReason "length" means the model hit its output-token
        // cap (maxTokens) mid-generation, likely before calling submit_ptx.
        const msg = event.message || {};
        const usage = msg.usage;
        lastStopReason = msg.stopReason ?? null;
        process.stdout.write(RESET);
        const usageStr = usage
          ? `${usage.output} out` +
            (usage.reasoning != null ? ` (${usage.reasoning} reasoning)` : "") +
            `, ${usage.input} in`
          : "usage n/a";
        console.log(
          `\n${GRAY}[info] stop=${lastStopReason} | ${usageStr}${RESET}`,
        );
        if (lastStopReason === "length") {
          console.log(
            `${RED}[warning]${RESET} ${GRAY}Turn hit the model output-token limit ` +
              `(maxTokens) mid-generation, so it may have stopped before calling ` +
              `submit_ptx. Raise the model's maxTokens or lower thinkingLevel.${RESET}`,
          );
        }
        streamMode = null;
        break;
      }
    }
  });

  try {
    // prompt() resolves only after the full run (all turns + tool calls) ends.
    await session.prompt(contextMessage);
  } finally {
    session.dispose();
  }

  const best =
    tracker.bestSpeedup > 0 ? tracker.bestSpeedup.toFixed(3) + "x" : "none";
  console.log(`\n${GRAY}Done. Best passing speedup vs Triton: ${best}.${RESET}`);
  console.log(`${MAGENTA}Session saved to: ${sessionManager.getSessionFile()}${RESET}`);
  if (lastStopReason === "length") {
    console.log(
      `${RED}Note:${RESET} ${GRAY}the run ended on a truncated turn (output-token ` +
        `limit), not because the model chose to stop.${RESET}`,
    );
  }
}

main().catch((err) => {
  console.error(`${RED}Fatal:${RESET} ${err.stack || err.message}`);
  process.exitCode = 1;
});
