"""Minimal baseline agent that optimizes a single Triton kernel at the PTX level.

The agent talks to a generic OpenAI-compatible chat completions endpoint and
interacts with the environment solely through ``triton_api``. It is deliberately
bare: one system prompt, one tool (``submit_ptx``), no skills, no structured
outputs, no test-time-scaling machinery.

Usage:
    python baseline_agent.py <KernelId>

Environment variables:
    LLM_BASE_URL  Base URL of the chat completions API (default: OpenAI).
    LLM_API_KEY   API key (falls back to OPENAI_API_KEY).
    LLM_MODEL     Model name (default: gpt-5.6-terra).
"""

from __future__ import annotations

import argparse
import json
import os
import sys

from openai import OpenAI

from triton_api import dump_kernel_ptx, evaluate_candidate, get_kernel_data

# --- Colors ---

RESET = "\x1b[0m"
BLUE = "\x1b[34m"
GREEN = "\x1b[32m"
RED = "\x1b[31m"
GRAY = "\x1b[90m"
CYAN = "\x1b[36m"

MAX_ITERATIONS = 40

SYSTEM_PROMPT = (
    "You are an expert GPU engineer optimizing a single Triton kernel at the "
    "NVIDIA PTX (assembly) level. You are given the Triton source, the PTX "
    "signature, the launch configuration, and the reference PTX that Triton "
    "generates.\n\n"
    "Your goal is to produce PTX that is functionally identical to the "
    "reference but runs faster. Call submit_ptx to compile, verify, and "
    "benchmark a candidate; it returns whether it compiled, whether it is "
    "correct, its p50 latency, and its speedup versus Triton. Iterate: read "
    "the result, fix errors, and keep trying to improve the speedup while "
    "staying correct. Only correct (passing) candidates count. When you are "
    "satisfied that you cannot improve further, stop and summarize your best "
    "result."
)

# --- Environment context ---


def build_context_message(kernel_id: str) -> str:
    """Assemble the kernel context handed to the model in the first turn."""
    data = get_kernel_data(kernel_id)
    reference_ptx = dump_kernel_ptx(kernel_id)
    if not reference_ptx:
        raise RuntimeError(f"Triton did not produce reference PTX for {kernel_id}.")

    system = data["system"]
    signature = "\n".join(
        f"  {param['name']}: {param['ptx_type']}" for param in data["ptx_signature"]
    )
    default_threads_x = data["num_warps"] * 32

    return (
        f"Kernel to optimize: {kernel_id}\n"
        f"PTX kernel name: {data['kernel_name']}\n\n"
        f"Target: {system['target']} | PTX version: {system['version']} | "
        f"address size: {system['address_size']}\n"
        f"num_warps: {data['num_warps']} "
        f"(reference launch uses num_threads_x = {default_threads_x})\n\n"
        "PTX parameter signature:\n"
        f"{signature}\n\n"
        "Triton source:\n"
        "```python\n"
        f"{data['source']}\n"
        "```\n\n"
        "Reference PTX generated by Triton (a correct starting point):\n"
        "```ptx\n"
        f"{reference_ptx}\n"
        "```\n\n"
        "Submit an optimized PTX candidate with submit_ptx."
    )


# --- Tool ---

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "submit_ptx",
            "description": (
                "Compile, verify, and benchmark a PTX candidate for the kernel. "
                "Returns whether it compiled, whether it is correct, its p50 "
                "latency, and its speedup versus the Triton baseline."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "ptx": {
                        "type": "string",
                        "description": "The full PTX module source for the candidate.",
                    },
                    "num_threads_x": {
                        "type": "integer",
                        "description": "Number of threads per block along x (required).",
                    },
                    "num_threads_y": {
                        "type": "integer",
                        "description": "Number of threads per block along y (optional).",
                    },
                    "num_threads_z": {
                        "type": "integer",
                        "description": "Number of threads per block along z (optional).",
                    },
                },
                "required": ["ptx", "num_threads_x"],
                "additionalProperties": False,
            },
        },
    }
]


def run_submit_ptx(kernel_id: str, arguments: str) -> str:
    """Evaluate a candidate and return a trimmed, JSON-serializable result."""
    try:
        payload = json.loads(arguments)
    except json.JSONDecodeError as exc:
        return json.dumps({"error": f"Invalid tool arguments: {exc}"})

    if not isinstance(payload, dict) or "ptx" not in payload:
        return json.dumps({"error": 'Arguments must include "ptx" and "num_threads_x".'})

    try:
        result = evaluate_candidate(kernel_id, payload)
    except Exception as exc:  # surface environment errors back to the model
        return json.dumps({"error": f"Evaluation failed: {exc}"})

    return json.dumps(
        {
            "passed": result.passed,
            "compiles": result.compiles,
            "correct": result.correct,
            "p50": result.p50,
            "speedup_vs_triton": result.speedup_vs_triton,
            "message": result.message,
            "compile_error": result.compile_error,
            "timing_error": result.timing_error,
        },
        indent=2,
    )


# --- Agent loop ---


def extract_reasoning(message) -> str | None:
    """Return the model's reasoning text if the backend exposes it.

    Chat completions has no reasoning role or class: reasoning arrives as an
    extra string field on the assistant message, named ``reasoning_content``
    (vLLM/DeepSeek style) or ``reasoning`` (OpenRouter style). It is absent on
    backends that do not surface it (e.g. OpenAI's own endpoint).
    """
    return getattr(message, "reasoning_content", None) or getattr(
        message, "reasoning", None
    )


def reasoning_message(reasoning: str) -> dict:
    """Wrap reasoning text as a user-role message so it persists in context."""
    return {
        "role": "user",
        "content": f"Your reasoning for the previous step:\n{reasoning}",
    }


def run_agent(client: OpenAI, model: str, kernel_id: str) -> None:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": build_context_message(kernel_id)},
    ]

    for iteration in range(1, MAX_ITERATIONS + 1):
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            tools=TOOLS,
            tool_choice="auto",
        )
        message = response.choices[0].message
        reasoning = extract_reasoning(message)

        # Append the assistant turn without the backend-specific reasoning
        # field, so we do not echo it back on an input field some APIs reject.
        assistant_message = message.model_dump(exclude_none=True)
        assistant_message.pop("reasoning_content", None)
        assistant_message.pop("reasoning", None)
        messages.append(assistant_message)

        if reasoning:
            print(f"\n{GRAY}[reasoning]{RESET} {GRAY}{reasoning}{RESET}")

        tool_calls = message.tool_calls or []
        if not tool_calls:
            if message.content:
                print(f"\n{CYAN}Agent:{RESET} {message.content}\n")
            if reasoning:
                messages.append(reasoning_message(reasoning))
            print(f"{GRAY}Agent stopped after {iteration} iteration(s).{RESET}")
            return

        for call in tool_calls:
            name = call.function.name
            args = call.function.arguments
            print(f"\n{BLUE}[call]{RESET} {GRAY}{name}(...){RESET}")

            if name == "submit_ptx":
                output = run_submit_ptx(kernel_id, args)
            else:
                output = json.dumps({"error": f"Unknown tool: {name}"})

            tag = f"{RED}[error]{RESET}" if '"error"' in output else f"{GREEN}[ok]{RESET}"
            print(f"{tag} {GRAY}{output}{RESET}")

            messages.append(
                {"role": "tool", "tool_call_id": call.id, "content": output}
            )

        # An assistant message with tool_calls must be immediately followed by
        # its tool results, so the reasoning is re-injected only after them.
        if reasoning:
            messages.append(reasoning_message(reasoning))

    print(f"{GRAY}Reached the {MAX_ITERATIONS}-iteration cap; stopping.{RESET}")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Baseline agent that optimizes a single Triton kernel's PTX."
    )
    parser.add_argument("kernel", help="Kernel class name, for example AddKernel.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    base_url = os.environ.get("LLM_BASE_URL")
    api_key = os.environ.get("LLM_API_KEY") or os.environ.get("OPENAI_API_KEY")
    model = os.environ.get("LLM_MODEL", "gpt-5.6-terra")

    client = OpenAI(base_url=base_url, api_key=api_key)

    print(f"Optimizing kernel {args.kernel!r} with model {model!r}", flush=True)
    run_agent(client, model, args.kernel)
    return 0


if __name__ == "__main__":
    sys.exit(main())
